import 'package:billing_system/features/inventory/data/models/inventory_product.dart';

class RetailStoreDummyProducts {
  static List<InventoryProductModel> getDummyProducts() {
    return [
      // ===== FRUITS & VEGETABLES (10 products) =====
      InventoryProductModel(
        id: 'prod_001',
        name: 'Fresh Apples (1kg)',
        sku: 'SKU-FA-001',
        barcode: '8901234567890',
        category: 'Fruits & Vegetables',
        purchasePrice: 85.00,
        price: 120.00,
        stock: 150,
        stockUnit: 'kg',
        supplier: 'Fresh Farms',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Apples)',
      ),
      InventoryProductModel(
        id: 'prod_002',
        name: 'Bananas (Bunch)',
        sku: 'SKU-FA-002',
        barcode: '8901234567891',
        category: 'Fruits & Vegetables',
        purchasePrice: 40.00,
        price: 60.00,
        stock: 200,
        stockUnit: 'kg',
        supplier: 'Fresh Farms',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Bananas)',
      ),
      InventoryProductModel(
        id: 'prod_003',
        name: 'Tomatoes (1kg)',
        sku: 'SKU-FA-003',
        barcode: '8901234567892',
        category: 'Fruits & Vegetables',
        purchasePrice: 32.00,
        price: 50.00,
        stock: 300,
        stockUnit: 'kg',
        supplier: 'Vegetable Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Tomatoes)',
      ),
      InventoryProductModel(
        id: 'prod_004',
        name: 'Onions (1kg)',
        sku: 'SKU-FA-004',
        barcode: '8901234567893',
        category: 'Fruits & Vegetables',
        purchasePrice: 25.00,
        price: 40.00,
        stock: 400,
        stockUnit: 'kg',
        supplier: 'Vegetable Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Onions)',
      ),
      InventoryProductModel(
        id: 'prod_005',
        name: 'Potatoes (1kg)',
        sku: 'SKU-FA-005',
        barcode: '8901234567894',
        category: 'Fruits & Vegetables',
        purchasePrice: 22.00,
        price: 35.00,
        stock: 450,
        stockUnit: 'kg',
        supplier: 'Vegetable Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Potatoes)',
      ),
      InventoryProductModel(
        id: 'prod_006',
        name: 'Carrots (1kg)',
        sku: 'SKU-FA-006',
        barcode: '8901234567895',
        category: 'Fruits & Vegetables',
        purchasePrice: 30.00,
        price: 45.00,
        stock: 250,
        stockUnit: 'kg',
        supplier: 'Vegetable Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Carrots)',
      ),
      InventoryProductModel(
        id: 'prod_007',
        name: 'Cucumber (1kg)',
        sku: 'SKU-FA-007',
        barcode: '8901234567896',
        category: 'Fruits & Vegetables',
        purchasePrice: 18.00,
        price: 30.00,
        stock: 200,
        stockUnit: 'kg',
        supplier: 'Vegetable Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Cucumber)',
      ),
      InventoryProductModel(
        id: 'prod_008',
        name: 'Bell Peppers (1kg)',
        sku: 'SKU-FA-008',
        barcode: '8901234567897',
        category: 'Fruits & Vegetables',
        purchasePrice: 55.00,
        price: 80.00,
        stock: 150,
        stockUnit: 'kg',
        supplier: 'Vegetable Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Bell+Peppers)',
      ),
      InventoryProductModel(
        id: 'prod_009',
        name: 'Spinach (500g)',
        sku: 'SKU-FA-009',
        barcode: '8901234567898',
        category: 'Fruits & Vegetables',
        purchasePrice: 24.00,
        price: 40.00,
        stock: 180,
        stockUnit: 'pcs',
        supplier: 'Fresh Farms',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Spinach)',
      ),
      InventoryProductModel(
        id: 'prod_010',
        name: 'Garlic (500g)',
        sku: 'SKU-FA-010',
        barcode: '8901234567899',
        category: 'Fruits & Vegetables',
        purchasePrice: 32.00,
        price: 50.00,
        stock: 220,
        stockUnit: 'pcs',
        supplier: 'Vegetable Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Garlic)',
      ),

      // ===== DAIRY (10 products) =====
      InventoryProductModel(
        id: 'prod_011',
        name: 'Whole Milk (1L)',
        sku: 'SKU-DA-011',
        barcode: '8901234567900',
        category: 'Dairy',
        purchasePrice: 42.00,
        price: 60.00,
        stock: 300,
        stockUnit: 'liter',
        supplier: 'Dairy Farms',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Milk)',
      ),
      InventoryProductModel(
        id: 'prod_012',
        name: 'Yogurt (500g)',
        sku: 'SKU-DA-012',
        barcode: '8901234567901',
        category: 'Dairy',
        purchasePrice: 30.00,
        price: 45.00,
        stock: 250,
        stockUnit: 'pcs',
        supplier: 'Dairy Farms',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Yogurt)',
      ),
      InventoryProductModel(
        id: 'prod_013',
        name: 'Paneer (250g)',
        sku: 'SKU-DA-013',
        barcode: '8901234567902',
        category: 'Dairy',
        purchasePrice: 85.00,
        price: 120.00,
        stock: 150,
        stockUnit: 'pcs',
        supplier: 'Dairy Farms',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Paneer)',
      ),
      InventoryProductModel(
        id: 'prod_014',
        name: 'Cheese (200g)',
        sku: 'SKU-DA-014',
        barcode: '8901234567903',
        category: 'Dairy',
        purchasePrice: 130.00,
        price: 180.00,
        stock: 100,
        stockUnit: 'pcs',
        supplier: 'Dairy Farms',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Cheese)',
      ),
      InventoryProductModel(
        id: 'prod_015',
        name: 'Butter (100g)',
        sku: 'SKU-DA-015',
        barcode: '8901234567904',
        category: 'Dairy',
        purchasePrice: 62.00,
        price: 90.00,
        stock: 200,
        stockUnit: 'pcs',
        supplier: 'Dairy Farms',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Butter)',
      ),
      InventoryProductModel(
        id: 'prod_016',
        name: 'Condensed Milk (400g)',
        sku: 'SKU-DA-016',
        barcode: '8901234567905',
        category: 'Dairy',
        purchasePrice: 48.00,
        price: 70.00,
        stock: 180,
        stockUnit: 'pcs',
        supplier: 'Dairy Brands',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Condensed+Milk)',
      ),
      InventoryProductModel(
        id: 'prod_017',
        name: 'Cream (200ml)',
        sku: 'SKU-DA-017',
        barcode: '8901234567906',
        category: 'Dairy',
        purchasePrice: 58.00,
        price: 85.00,
        stock: 140,
        stockUnit: 'pcs',
        supplier: 'Dairy Farms',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Cream)',
      ),
      InventoryProductModel(
        id: 'prod_018',
        name: 'Ice Cream (1L)',
        sku: 'SKU-DA-018',
        barcode: '8901234567907',
        category: 'Dairy',
        purchasePrice: 100.00,
        price: 150.00,
        stock: 120,
        stockUnit: 'pcs',
        supplier: 'Ice Cream Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Ice+Cream)',
      ),
      InventoryProductModel(
        id: 'prod_019',
        name: 'Curd (500g)',
        sku: 'SKU-DA-019',
        barcode: '8901234567908',
        category: 'Dairy',
        purchasePrice: 27.00,
        price: 40.00,
        stock: 220,
        stockUnit: 'pcs',
        supplier: 'Dairy Farms',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Curd)',
      ),
      InventoryProductModel(
        id: 'prod_020',
        name: 'Mozzarella Cheese (200g)',
        sku: 'SKU-DA-020',
        barcode: '8901234567909',
        category: 'Dairy',
        purchasePrice: 145.00,
        price: 200.00,
        stock: 80,
        stockUnit: 'pcs',
        supplier: 'Dairy Brands',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Mozzarella)',
      ),

      // ===== BAKERY (8 products) =====
      InventoryProductModel(
        id: 'prod_021',
        name: 'Whole Wheat Bread',
        sku: 'SKU-BA-021',
        barcode: '8901234567910',
        category: 'Bakery',
        purchasePrice: 25.00,
        price: 40.00,
        stock: 150,
        stockUnit: 'pcs',
        supplier: 'Fresh Bakery',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Wheat+Bread)',
      ),
      InventoryProductModel(
        id: 'prod_022',
        name: 'White Bread',
        sku: 'SKU-BA-022',
        barcode: '8901234567911',
        category: 'Bakery',
        purchasePrice: 22.00,
        price: 35.00,
        stock: 180,
        stockUnit: 'pcs',
        supplier: 'Fresh Bakery',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=White+Bread)',
      ),
      InventoryProductModel(
        id: 'prod_023',
        name: 'Croissants (Pack of 4)',
        sku: 'SKU-BA-023',
        barcode: '8901234567912',
        category: 'Bakery',
        purchasePrice: 80.00,
        price: 120.00,
        stock: 100,
        stockUnit: 'pcs',
        supplier: 'Fresh Bakery',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Croissants)',
      ),
      InventoryProductModel(
        id: 'prod_024',
        name: 'Donuts (Pack of 6)',
        sku: 'SKU-BA-024',
        barcode: '8901234567913',
        category: 'Bakery',
        purchasePrice: 68.00,
        price: 100.00,
        stock: 120,
        stockUnit: 'pcs',
        supplier: 'Fresh Bakery',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Donuts)',
      ),
      InventoryProductModel(
        id: 'prod_025',
        name: 'Cake (500g)',
        sku: 'SKU-BA-025',
        barcode: '8901234567914',
        category: 'Bakery',
        purchasePrice: 170.00,
        price: 250.00,
        stock: 60,
        stockUnit: 'pcs',
        supplier: 'Fresh Bakery',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Cake)',
      ),
      InventoryProductModel(
        id: 'prod_026',
        name: 'Cookies (200g)',
        sku: 'SKU-BA-026',
        barcode: '8901234567915',
        category: 'Bakery',
        purchasePrice: 52.00,
        price: 80.00,
        stock: 180,
        stockUnit: 'pcs',
        supplier: 'Fresh Bakery',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Cookies)',
      ),
      InventoryProductModel(
        id: 'prod_027',
        name: 'Muffins (Pack of 4)',
        sku: 'SKU-BA-027',
        barcode: '8901234567916',
        category: 'Bakery',
        purchasePrice: 75.00,
        price: 110.00,
        stock: 90,
        stockUnit: 'pcs',
        supplier: 'Fresh Bakery',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Muffins)',
      ),
      InventoryProductModel(
        id: 'prod_028',
        name: 'Baguette',
        sku: 'SKU-BA-028',
        barcode: '8901234567917',
        category: 'Bakery',
        purchasePrice: 38.00,
        price: 60.00,
        stock: 120,
        stockUnit: 'pcs',
        supplier: 'Fresh Bakery',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Baguette)',
      ),

      // ===== GROCERY (12 products) =====
      InventoryProductModel(
        id: 'prod_029',
        name: 'Basmati Rice (1kg)',
        sku: 'SKU-GR-029',
        barcode: '8901234567918',
        category: 'Grocery',
        purchasePrice: 58.00,
        price: 80.00,
        stock: 300,
        stockUnit: 'kg',
        supplier: 'Rice Traders',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Rice)',
      ),
      InventoryProductModel(
        id: 'prod_030',
        name: 'Sunflower Oil (1L)',
        sku: 'SKU-GR-030',
        barcode: '8901234567919',
        category: 'Grocery',
        purchasePrice: 155.00,
        price: 200.00,
        stock: 200,
        stockUnit: 'liter',
        supplier: 'Oil Producers',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Oil)',
      ),
      InventoryProductModel(
        id: 'prod_031',
        name: 'Sugar (1kg)',
        sku: 'SKU-GR-031',
        barcode: '8901234567920',
        category: 'Grocery',
        purchasePrice: 38.00,
        price: 55.00,
        stock: 250,
        stockUnit: 'pcs',
        supplier: 'Sugar Mills',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Sugar)',
      ),
      InventoryProductModel(
        id: 'prod_032',
        name: 'Wheat Flour (1kg)',
        sku: 'SKU-GR-032',
        barcode: '8901234567921',
        category: 'Grocery',
        purchasePrice: 30.00,
        price: 45.00,
        stock: 350,
        stockUnit: 'kg',
        supplier: 'Flour Mills',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Flour)',
      ),
      InventoryProductModel(
        id: 'prod_033',
        name: 'Lentils (500g)',
        sku: 'SKU-GR-033',
        barcode: '8901234567922',
        category: 'Grocery',
        purchasePrice: 82.00,
        price: 120.00,
        stock: 200,
        stockUnit: 'pcs',
        supplier: 'Lentil Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Lentils)',
      ),
      InventoryProductModel(
        id: 'prod_034',
        name: 'Chickpeas (500g)',
        sku: 'SKU-GR-034',
        barcode: '8901234567923',
        category: 'Grocery',
        purchasePrice: 68.00,
        price: 100.00,
        stock: 180,
        stockUnit: 'pcs',
        supplier: 'Lentil Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Chickpeas)',
      ),
      InventoryProductModel(
        id: 'prod_035',
        name: 'Salt (1kg)',
        sku: 'SKU-GR-035',
        barcode: '8901234567924',
        category: 'Grocery',
        purchasePrice: 16.00,
        price: 25.00,
        stock: 400,
        stockUnit: 'pcs',
        supplier: 'Salt Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Salt)',
      ),
      InventoryProductModel(
        id: 'prod_036',
        name: 'Tea Leaves (500g)',
        sku: 'SKU-GR-036',
        barcode: '8901234567925',
        category: 'Grocery',
        purchasePrice: 180.00,
        price: 250.00,
        stock: 150,
        stockUnit: 'pcs',
        supplier: 'Tea Gardens',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Tea)',
      ),
      InventoryProductModel(
        id: 'prod_037',
        name: 'Coffee Beans (500g)',
        sku: 'SKU-GR-037',
        barcode: '8901234567926',
        category: 'Grocery',
        purchasePrice: 260.00,
        price: 350.00,
        stock: 100,
        stockUnit: 'pcs',
        supplier: 'Coffee Estates',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Coffee)',
      ),
      InventoryProductModel(
        id: 'prod_038',
        name: 'Spice Mix (100g)',
        sku: 'SKU-GR-038',
        barcode: '8901234567927',
        category: 'Grocery',
        purchasePrice: 52.00,
        price: 80.00,
        stock: 220,
        stockUnit: 'pcs',
        supplier: 'Spice House',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Spices)',
      ),
      InventoryProductModel(
        id: 'prod_039',
        name: 'Pasta (500g)',
        sku: 'SKU-GR-039',
        barcode: '8901234567928',
        category: 'Grocery',
        purchasePrice: 62.00,
        price: 90.00,
        stock: 180,
        stockUnit: 'pcs',
        supplier: 'Pasta Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Pasta)',
      ),
      InventoryProductModel(
        id: 'prod_040',
        name: 'Tomato Sauce (400g)',
        sku: 'SKU-GR-040',
        barcode: '8901234567929',
        category: 'Grocery',
        purchasePrice: 42.00,
        price: 60.00,
        stock: 250,
        stockUnit: 'pcs',
        supplier: 'Sauce Makers',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Sauce)',
      ),

      // ===== BEVERAGES (10 products) =====
      InventoryProductModel(
        id: 'prod_041',
        name: 'Orange Juice (1L)',
        sku: 'SKU-BE-041',
        barcode: '8901234567930',
        category: 'Beverages',
        purchasePrice: 68.00,
        price: 100.00,
        stock: 200,
        stockUnit: 'liter',
        supplier: 'Juice Masters',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Orange+Juice)',
      ),
      InventoryProductModel(
        id: 'prod_042',
        name: 'Mineral Water (2L)',
        sku: 'SKU-BE-042',
        barcode: '8901234567931',
        category: 'Beverages',
        purchasePrice: 28.00,
        price: 50.00,
        stock: 500,
        stockUnit: 'pcs',
        supplier: 'Water Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Water)',
      ),
      InventoryProductModel(
        id: 'prod_043',
        name: 'Cola (500ml)',
        sku: 'SKU-BE-043',
        barcode: '8901234567932',
        category: 'Beverages',
        purchasePrice: 24.00,
        price: 40.00,
        stock: 400,
        stockUnit: 'pcs',
        supplier: 'Soda Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Cola)',
      ),
      InventoryProductModel(
        id: 'prod_044',
        name: 'Lemonade (1L)',
        sku: 'SKU-BE-044',
        barcode: '8901234567933',
        category: 'Beverages',
        purchasePrice: 55.00,
        price: 80.00,
        stock: 250,
        stockUnit: 'liter',
        supplier: 'Juice Masters',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Lemonade)',
      ),
      InventoryProductModel(
        id: 'prod_045',
        name: 'Iced Tea (500ml)',
        sku: 'SKU-BE-045',
        barcode: '8901234567934',
        category: 'Beverages',
        purchasePrice: 40.00,
        price: 60.00,
        stock: 300,
        stockUnit: 'pcs',
        supplier: 'Tea Brands',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Iced+Tea)',
      ),
      InventoryProductModel(
        id: 'prod_046',
        name: 'Energy Drink (250ml)',
        sku: 'SKU-BE-046',
        barcode: '8901234567935',
        category: 'Beverages',
        purchasePrice: 68.00,
        price: 100.00,
        stock: 280,
        stockUnit: 'pcs',
        supplier: 'Energy Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Energy+Drink)',
      ),
      InventoryProductModel(
        id: 'prod_047',
        name: 'Kombucha (500ml)',
        sku: 'SKU-BE-047',
        barcode: '8901234567936',
        category: 'Beverages',
        purchasePrice: 105.00,
        price: 150.00,
        stock: 120,
        stockUnit: 'pcs',
        supplier: 'Health Drinks',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Kombucha)',
      ),
      InventoryProductModel(
        id: 'prod_048',
        name: 'Coffee (Ready to Drink)',
        sku: 'SKU-BE-048',
        barcode: '8901234567937',
        category: 'Beverages',
        purchasePrice: 46.00,
        price: 70.00,
        stock: 200,
        stockUnit: 'pcs',
        supplier: 'Coffee Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Ready+Coffee)',
      ),
      InventoryProductModel(
        id: 'prod_049',
        name: 'Milk Shake Mix (200g)',
        sku: 'SKU-BE-049',
        barcode: '8901234567938',
        category: 'Beverages',
        purchasePrice: 82.00,
        price: 120.00,
        stock: 160,
        stockUnit: 'pcs',
        supplier: 'Beverage Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Shake+Mix)',
      ),
      InventoryProductModel(
        id: 'prod_050',
        name: 'Fruit Punch (1L)',
        sku: 'SKU-BE-050',
        barcode: '8901234567939',
        category: 'Beverages',
        purchasePrice: 60.00,
        price: 90.00,
        stock: 220,
        stockUnit: 'pcs',
        supplier: 'Juice Masters',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Fruit+Punch)',
      ),

      // ===== SNACKS (10 products) =====
      InventoryProductModel(
        id: 'prod_051',
        name: 'Potato Chips (150g)',
        sku: 'SKU-SN-051',
        barcode: '8901234567940',
        category: 'Snacks',
        purchasePrice: 28.00,
        price: 45.00,
        stock: 300,
        stockUnit: 'pcs',
        supplier: 'Snack Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Chips)',
      ),
      InventoryProductModel(
        id: 'prod_052',
        name: 'Popcorn (100g)',
        sku: 'SKU-SN-052',
        barcode: '8901234567941',
        category: 'Snacks',
        purchasePrice: 32.00,
        price: 50.00,
        stock: 250,
        stockUnit: 'pcs',
        supplier: 'Snack Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Popcorn)',
      ),
      InventoryProductModel(
        id: 'prod_053',
        name: 'Namkeen Mix (200g)',
        sku: 'SKU-SN-053',
        barcode: '8901234567942',
        category: 'Snacks',
        purchasePrice: 38.00,
        price: 60.00,
        stock: 220,
        stockUnit: 'pcs',
        supplier: 'Snack Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Namkeen)',
      ),
      InventoryProductModel(
        id: 'prod_054',
        name: 'Cookies (300g)',
        sku: 'SKU-SN-054',
        barcode: '8901234567943',
        category: 'Snacks',
        purchasePrice: 60.00,
        price: 90.00,
        stock: 200,
        stockUnit: 'pcs',
        supplier: 'Cookie Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Cookies)',
      ),
      InventoryProductModel(
        id: 'prod_055',
        name: 'Chocolate Bar',
        sku: 'SKU-SN-055',
        barcode: '8901234567944',
        category: 'Snacks',
        purchasePrice: 24.00,
        price: 40.00,
        stock: 350,
        stockUnit: 'pcs',
        supplier: 'Chocolate Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Chocolate)',
      ),
      InventoryProductModel(
        id: 'prod_056',
        name: 'Granola Bars (Pack of 5)',
        sku: 'SKU-SN-056',
        barcode: '8901234567945',
        category: 'Snacks',
        purchasePrice: 68.00,
        price: 100.00,
        stock: 180,
        stockUnit: 'pcs',
        supplier: 'Health Snacks',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Granola)',
      ),
      InventoryProductModel(
        id: 'prod_057',
        name: 'Almonds (200g)',
        sku: 'SKU-SN-057',
        barcode: '8901234567946',
        category: 'Snacks',
        purchasePrice: 185.00,
        price: 250.00,
        stock: 100,
        stockUnit: 'pcs',
        supplier: 'Nuts Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Almonds)',
      ),
      InventoryProductModel(
        id: 'prod_058',
        name: 'Cashews (200g)',
        sku: 'SKU-SN-058',
        barcode: '8901234567947',
        category: 'Snacks',
        purchasePrice: 225.00,
        price: 300.00,
        stock: 80,
        stockUnit: 'pcs',
        supplier: 'Nuts Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Cashews)',
      ),
      InventoryProductModel(
        id: 'prod_059',
        name: 'Dried Fruits Mix (150g)',
        sku: 'SKU-SN-059',
        barcode: '8901234567948',
        category: 'Snacks',
        purchasePrice: 145.00,
        price: 200.00,
        stock: 120,
        stockUnit: 'pcs',
        supplier: 'Dry Fruits Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Dried+Fruits)',
      ),
      InventoryProductModel(
        id: 'prod_060',
        name: 'Wafers (100g)',
        sku: 'SKU-SN-060',
        barcode: '8901234567949',
        category: 'Snacks',
        purchasePrice: 22.00,
        price: 35.00,
        stock: 280,
        stockUnit: 'pcs',
        supplier: 'Snack Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Wafers)',
      ),

      // ===== INSTANT FOOD (8 products) =====
      InventoryProductModel(
        id: 'prod_061',
        name: 'Instant Noodles (85g)',
        sku: 'SKU-IF-061',
        barcode: '8901234567950',
        category: 'Instant Food',
        purchasePrice: 16.00,
        price: 25.00,
        stock: 500,
        stockUnit: 'pcs',
        supplier: 'Noodle Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Noodles)',
      ),
      InventoryProductModel(
        id: 'prod_062',
        name: 'Canned Soup (400g)',
        sku: 'SKU-IF-062',
        barcode: '8901234567951',
        category: 'Instant Food',
        purchasePrice: 55.00,
        price: 80.00,
        stock: 200,
        stockUnit: 'pcs',
        supplier: 'Soup Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Soup)',
      ),
      InventoryProductModel(
        id: 'prod_063',
        name: 'Instant Rice (200g)',
        sku: 'SKU-IF-063',
        barcode: '8901234567952',
        category: 'Instant Food',
        purchasePrice: 40.00,
        price: 60.00,
        stock: 250,
        stockUnit: 'pcs',
        supplier: 'Rice Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Instant+Rice)',
      ),
      InventoryProductModel(
        id: 'prod_064',
        name: 'Frozen Pizza (400g)',
        sku: 'SKU-IF-064',
        barcode: '8901234567953',
        category: 'Instant Food',
        purchasePrice: 125.00,
        price: 180.00,
        stock: 120,
        stockUnit: 'pcs',
        supplier: 'Pizza Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Pizza)',
      ),
      InventoryProductModel(
        id: 'prod_065',
        name: 'Instant Oats (400g)',
        sku: 'SKU-IF-065',
        barcode: '8901234567954',
        category: 'Instant Food',
        purchasePrice: 82.00,
        price: 120.00,
        stock: 180,
        stockUnit: 'pcs',
        supplier: 'Cereal Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Oats)',
      ),
      InventoryProductModel(
        id: 'prod_066',
        name: 'Ready Mix Cake (300g)',
        sku: 'SKU-IF-066',
        barcode: '8901234567955',
        category: 'Instant Food',
        purchasePrice: 68.00,
        price: 100.00,
        stock: 150,
        stockUnit: 'pcs',
        supplier: 'Baking Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Cake+Mix)',
      ),
      InventoryProductModel(
        id: 'prod_067',
        name: 'Instant Dosa Mix (500g)',
        sku: 'SKU-IF-067',
        barcode: '8901234567956',
        category: 'Instant Food',
        purchasePrice: 54.00,
        price: 80.00,
        stock: 200,
        stockUnit: 'pcs',
        supplier: 'Food Mix Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Dosa+Mix)',
      ),
      InventoryProductModel(
        id: 'prod_068',
        name: 'Cornflakes (300g)',
        sku: 'SKU-IF-068',
        barcode: '8901234567957',
        category: 'Instant Food',
        purchasePrice: 60.00,
        price: 90.00,
        stock: 220,
        stockUnit: 'pcs',
        supplier: 'Cereal Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Cornflakes)',
      ),

      // ===== MEAT & SEAFOOD (6 products) =====
      InventoryProductModel(
        id: 'prod_069',
        name: 'Chicken Breast (1kg)',
        sku: 'SKU-MS-069',
        barcode: '8901234567958',
        category: 'Meat & Seafood',
        purchasePrice: 220.00,
        price: 300.00,
        stock: 100,
        stockUnit: 'kg',
        supplier: 'Fresh Meat Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Chicken)',
      ),
      InventoryProductModel(
        id: 'prod_070',
        name: 'Mutton (1kg)',
        sku: 'SKU-MS-070',
        barcode: '8901234567959',
        category: 'Meat & Seafood',
        purchasePrice: 340.00,
        price: 450.00,
        stock: 60,
        stockUnit: 'kg',
        supplier: 'Fresh Meat Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Mutton)',
      ),
      InventoryProductModel(
        id: 'prod_071',
        name: 'Fish (1kg)',
        sku: 'SKU-MS-071',
        barcode: '8901234567960',
        category: 'Meat & Seafood',
        purchasePrice: 260.00,
        price: 350.00,
        stock: 80,
        stockUnit: 'kg',
        supplier: 'Seafood Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Fish)',
      ),
      InventoryProductModel(
        id: 'prod_072',
        name: 'Prawns (500g)',
        sku: 'SKU-MS-072',
        barcode: '8901234567961',
        category: 'Meat & Seafood',
        purchasePrice: 290.00,
        price: 400.00,
        stock: 50,
        stockUnit: 'pcs',
        supplier: 'Seafood Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Prawns)',
      ),
      InventoryProductModel(
        id: 'prod_073',
        name: 'Eggs (12 pcs)',
        sku: 'SKU-MS-073',
        barcode: '8901234567962',
        category: 'Meat & Seafood',
        purchasePrice: 58.00,
        price: 80.00,
        stock: 300,
        stockUnit: 'pcs',
        supplier: 'Egg Farms',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Eggs)',
      ),
      InventoryProductModel(
        id: 'prod_074',
        name: 'Canned Tuna (200g)',
        sku: 'SKU-MS-074',
        barcode: '8901234567963',
        category: 'Meat & Seafood',
        purchasePrice: 82.00,
        price: 120.00,
        stock: 200,
        stockUnit: 'pcs',
        supplier: 'Seafood Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Tuna)',
      ),

      // ===== ELECTRONICS (10 products) =====
      InventoryProductModel(
        id: 'prod_075',
        name: 'Wireless Headphones',
        sku: 'SKU-EL-075',
        barcode: '8901234567964',
        category: 'Electronics',
        purchasePrice: 1850.00,
        price: 2499.99,
        stock: 40,
        stockUnit: 'pcs',
        supplier: 'Tech Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Headphones)',
      ),
      InventoryProductModel(
        id: 'prod_076',
        name: 'USB-C Cable',
        sku: 'SKU-EL-076',
        barcode: '8901234567965',
        category: 'Electronics',
        purchasePrice: 180.00,
        price: 299.99,
        stock: 150,
        stockUnit: 'pcs',
        supplier: 'Cable Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=USB+Cable)',
      ),
      InventoryProductModel(
        id: 'prod_077',
        name: 'Power Bank 10000mAh',
        sku: 'SKU-EL-077',
        barcode: '8901234567966',
        category: 'Electronics',
        purchasePrice: 1180.00,
        price: 1599.99,
        stock: 60,
        stockUnit: 'pcs',
        supplier: 'PowerTech',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Power+Bank)',
      ),
      InventoryProductModel(
        id: 'prod_078',
        name: 'Screen Protector',
        sku: 'SKU-EL-078',
        barcode: '8901234567967',
        category: 'Electronics',
        purchasePrice: 110.00,
        price: 199.99,
        stock: 200,
        stockUnit: 'pcs',
        supplier: 'Glass Guard',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Protector)',
      ),
      InventoryProductModel(
        id: 'prod_079',
        name: 'Wireless Mouse',
        sku: 'SKU-EL-079',
        barcode: '8901234567968',
        category: 'Electronics',
        purchasePrice: 560.00,
        price: 799.99,
        stock: 80,
        stockUnit: 'pcs',
        supplier: 'Tech Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Mouse)',
      ),
      InventoryProductModel(
        id: 'prod_080',
        name: 'Keyboard',
        sku: 'SKU-EL-080',
        barcode: '8901234567969',
        category: 'Electronics',
        purchasePrice: 920.00,
        price: 1299.99,
        stock: 50,
        stockUnit: 'pcs',
        supplier: 'Tech Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Keyboard)',
      ),
      InventoryProductModel(
        id: 'prod_081',
        name: 'USB Hub (4 port)',
        sku: 'SKU-EL-081',
        barcode: '8901234567970',
        category: 'Electronics',
        purchasePrice: 420.00,
        price: 599.99,
        stock: 100,
        stockUnit: 'pcs',
        supplier: 'Tech Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=USB+Hub)',
      ),
      InventoryProductModel(
        id: 'prod_082',
        name: 'Phone Stand',
        sku: 'SKU-EL-082',
        barcode: '8901234567971',
        category: 'Electronics',
        purchasePrice: 250.00,
        price: 399.99,
        stock: 120,
        stockUnit: 'pcs',
        supplier: 'Accessories Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Phone+Stand)',
      ),
      InventoryProductModel(
        id: 'prod_083',
        name: 'Laptop Stand',
        sku: 'SKU-EL-083',
        barcode: '8901234567972',
        category: 'Electronics',
        purchasePrice: 620.00,
        price: 899.99,
        stock: 60,
        stockUnit: 'pcs',
        supplier: 'Accessories Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Laptop+Stand)',
      ),
      InventoryProductModel(
        id: 'prod_084',
        name: 'HDMI Cable',
        sku: 'SKU-EL-084',
        barcode: '8901234567973',
        category: 'Electronics',
        purchasePrice: 210.00,
        price: 349.99,
        stock: 140,
        stockUnit: 'pcs',
        supplier: 'Cable Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=HDMI+Cable)',
      ),

      // ===== CLOTHING & APPAREL (10 products) =====
      InventoryProductModel(
        id: 'prod_085',
        name: 'Cotton T-Shirt',
        sku: 'SKU-CL-085',
        barcode: '8901234567974',
        category: 'Clothing & Apparel',
        purchasePrice: 240.00,
        price: 399.99,
        stock: 150,
        stockUnit: 'pcs',
        supplier: 'Fashion Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=T-Shirt)',
      ),
      InventoryProductModel(
        id: 'prod_086',
        name: 'Denim Jeans',
        sku: 'SKU-CL-086',
        barcode: '8901234567975',
        category: 'Clothing & Apparel',
        purchasePrice: 850.00,
        price: 1299.99,
        stock: 80,
        stockUnit: 'pcs',
        supplier: 'Denim Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Jeans)',
      ),
      InventoryProductModel(
        id: 'prod_087',
        name: 'Casual Shirt',
        sku: 'SKU-CL-087',
        barcode: '8901234567976',
        category: 'Clothing & Apparel',
        purchasePrice: 460.00,
        price: 699.99,
        stock: 100,
        stockUnit: 'pcs',
        supplier: 'Fashion Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Shirt)',
      ),
      InventoryProductModel(
        id: 'prod_088',
        name: 'Cotton Socks (Pack of 3)',
        sku: 'SKU-CL-088',
        barcode: '8901234567977',
        category: 'Clothing & Apparel',
        purchasePrice: 120.00,
        price: 199.99,
        stock: 300,
        stockUnit: 'pcs',
        supplier: 'Comfort Wear',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Socks)',
      ),
      InventoryProductModel(
        id: 'prod_089',
        name: 'Underwear (Pack of 2)',
        sku: 'SKU-CL-089',
        barcode: '8901234567978',
        category: 'Clothing & Apparel',
        purchasePrice: 220.00,
        price: 349.99,
        stock: 200,
        stockUnit: 'pcs',
        supplier: 'Intimates Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Underwear)',
      ),
      InventoryProductModel(
        id: 'prod_090',
        name: 'Winter Jacket',
        sku: 'SKU-CL-090',
        barcode: '8901234567979',
        category: 'Clothing & Apparel',
        purchasePrice: 2450.00,
        price: 3499.99,
        stock: 40,
        stockUnit: 'pcs',
        supplier: 'Winter Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Jacket)',
      ),
      InventoryProductModel(
        id: 'prod_091',
        name: 'Shorts',
        sku: 'SKU-CL-091',
        barcode: '8901234567980',
        category: 'Clothing & Apparel',
        purchasePrice: 320.00,
        price: 499.99,
        stock: 120,
        stockUnit: 'pcs',
        supplier: 'Fashion Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Shorts)',
      ),
      InventoryProductModel(
        id: 'prod_092',
        name: 'Sweater',
        sku: 'SKU-CL-092',
        barcode: '8901234567981',
        category: 'Clothing & Apparel',
        purchasePrice: 620.00,
        price: 899.99,
        stock: 70,
        stockUnit: 'pcs',
        supplier: 'Knitwear Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Sweater)',
      ),
      InventoryProductModel(
        id: 'prod_093',
        name: 'Saree',
        sku: 'SKU-CL-093',
        barcode: '8901234567982',
        category: 'Clothing & Apparel',
        purchasePrice: 1450.00,
        price: 1999.99,
        stock: 50,
        stockUnit: 'pcs',
        supplier: 'Ethnic Wear',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Saree)',
      ),
      InventoryProductModel(
        id: 'prod_094',
        name: 'Kurta',
        sku: 'SKU-CL-094',
        barcode: '8901234567983',
        category: 'Clothing & Apparel',
        purchasePrice: 620.00,
        price: 899.99,
        stock: 90,
        stockUnit: 'pcs',
        supplier: 'Ethnic Wear',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Kurta)',
      ),

      // ===== FOOTWEAR (6 products) =====
      InventoryProductModel(
        id: 'prod_095',
        name: 'Sports Shoe',
        sku: 'SKU-FW-095',
        barcode: '8901234567984',
        category: 'Footwear',
        purchasePrice: 1750.00,
        price: 2499.99,
        stock: 60,
        stockUnit: 'pcs',
        supplier: 'Athletic Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Sports+Shoe)',
      ),
      InventoryProductModel(
        id: 'prod_096',
        name: 'Casual Shoe',
        sku: 'SKU-FW-096',
        barcode: '8901234567985',
        category: 'Footwear',
        purchasePrice: 1100.00,
        price: 1599.99,
        stock: 80,
        stockUnit: 'pcs',
        supplier: 'Shoe Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Casual+Shoe)',
      ),
      InventoryProductModel(
        id: 'prod_097',
        name: 'Formal Shoe',
        sku: 'SKU-FW-097',
        barcode: '8901234567986',
        category: 'Footwear',
        purchasePrice: 1380.00,
        price: 1999.99,
        stock: 50,
        stockUnit: 'pcs',
        supplier: 'Formal Wear',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Formal+Shoe)',
      ),
      InventoryProductModel(
        id: 'prod_098',
        name: 'Sandal',
        sku: 'SKU-FW-098',
        barcode: '8901234567987',
        category: 'Footwear',
        purchasePrice: 480.00,
        price: 699.99,
        stock: 150,
        stockUnit: 'pcs',
        supplier: 'Sandal Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Sandal)',
      ),
      InventoryProductModel(
        id: 'prod_099',
        name: 'Flip Flop',
        sku: 'SKU-FW-099',
        barcode: '8901234567988',
        category: 'Footwear',
        purchasePrice: 190.00,
        price: 299.99,
        stock: 200,
        stockUnit: 'pcs',
        supplier: 'Casual Wear',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Flip+Flop)',
      ),
      InventoryProductModel(
        id: 'prod_100',
        name: 'Boot',
        sku: 'SKU-FW-100',
        barcode: '8901234567989',
        category: 'Footwear',
        purchasePrice: 1600.00,
        price: 2299.99,
        stock: 40,
        stockUnit: 'pcs',
        supplier: 'Boot Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Boot)',
      ),

      // ===== HOUSEHOLD & CLEANING (10 products) =====
      InventoryProductModel(
        id: 'prod_101',
        name: 'Dish Washing Soap',
        sku: 'SKU-HC-101',
        barcode: '8901234567990',
        category: 'Household & Cleaning',
        purchasePrice: 50.00,
        price: 75.00,
        stock: 250,
        stockUnit: 'pcs',
        supplier: 'Cleaning Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Dish+Soap)',
      ),
      InventoryProductModel(
        id: 'prod_102',
        name: 'Laundry Detergent (2kg)',
        sku: 'SKU-HC-102',
        barcode: '8901234567991',
        category: 'Household & Cleaning',
        purchasePrice: 250.00,
        price: 350.00,
        stock: 180,
        stockUnit: 'pcs',
        supplier: 'Clean Brands',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Detergent)',
      ),
      InventoryProductModel(
        id: 'prod_103',
        name: 'Toilet Paper Roll (4 pcs)',
        sku: 'SKU-HC-103',
        barcode: '8901234567992',
        category: 'Household & Cleaning',
        purchasePrice: 78.00,
        price: 120.00,
        stock: 400,
        stockUnit: 'pcs',
        supplier: 'Paper Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Toilet+Paper)',
      ),
      InventoryProductModel(
        id: 'prod_104',
        name: 'Aluminum Foil Roll',
        sku: 'SKU-HC-104',
        barcode: '8901234567993',
        category: 'Household & Cleaning',
        purchasePrice: 65.00,
        price: 99.00,
        stock: 150,
        stockUnit: 'pcs',
        supplier: 'Aluminum Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Foil)',
      ),
      InventoryProductModel(
        id: 'prod_105',
        name: 'Light Bulb LED (9W)',
        sku: 'SKU-HC-105',
        barcode: '8901234567994',
        category: 'Household & Cleaning',
        purchasePrice: 105.00,
        price: 150.00,
        stock: 220,
        stockUnit: 'pcs',
        supplier: 'Lighting Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=LED+Bulb)',
      ),
      InventoryProductModel(
        id: 'prod_106',
        name: 'Floor Cleaner (1L)',
        sku: 'SKU-HC-106',
        barcode: '8901234567995',
        category: 'Household & Cleaning',
        purchasePrice: 82.00,
        price: 120.00,
        stock: 200,
        stockUnit: 'pcs',
        supplier: 'Cleaning Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Floor+Cleaner)',
      ),
      InventoryProductModel(
        id: 'prod_107',
        name: 'Glass Cleaner (500ml)',
        sku: 'SKU-HC-107',
        barcode: '8901234567996',
        category: 'Household & Cleaning',
        purchasePrice: 54.00,
        price: 80.00,
        stock: 250,
        stockUnit: 'pcs',
        supplier: 'Cleaning Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Glass+Cleaner)',
      ),
      InventoryProductModel(
        id: 'prod_108',
        name: 'Trash Bags (Roll of 20)',
        sku: 'SKU-HC-108',
        barcode: '8901234567997',
        category: 'Household & Cleaning',
        purchasePrice: 68.00,
        price: 100.00,
        stock: 300,
        stockUnit: 'pcs',
        supplier: 'Bags Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Trash+Bags)',
      ),
      InventoryProductModel(
        id: 'prod_109',
        name: 'Sponge Scrubber',
        sku: 'SKU-HC-109',
        barcode: '8901234567998',
        category: 'Household & Cleaning',
        purchasePrice: 24.00,
        price: 40.00,
        stock: 350,
        stockUnit: 'pcs',
        supplier: 'Cleaning Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Sponge)',
      ),
      InventoryProductModel(
        id: 'prod_110',
        name: 'Bleach (1L)',
        sku: 'SKU-HC-110',
        barcode: '8901234567999',
        category: 'Household & Cleaning',
        purchasePrice: 40.00,
        price: 60.00,
        stock: 220,
        stockUnit: 'pcs',
        supplier: 'Cleaning Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Bleach)',
      ),

      // ===== BEAUTY & PERSONAL CARE (8 products) =====
      InventoryProductModel(
        id: 'prod_111',
        name: 'Face Wash',
        sku: 'SKU-BP-111',
        barcode: '8901234568000',
        category: 'Beauty & Personal Care',
        purchasePrice: 170.00,
        price: 249.99,
        stock: 180,
        stockUnit: 'pcs',
        supplier: 'Skin Care',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Face+Wash)',
      ),
      InventoryProductModel(
        id: 'prod_112',
        name: 'Moisturizing Lotion',
        sku: 'SKU-BP-112',
        barcode: '8901234568001',
        category: 'Beauty & Personal Care',
        purchasePrice: 275.00,
        price: 399.99,
        stock: 140,
        stockUnit: 'pcs',
        supplier: 'Skin Care',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Moisturizer)',
      ),
      InventoryProductModel(
        id: 'prod_113',
        name: 'Toothpaste (200g)',
        sku: 'SKU-BP-113',
        barcode: '8901234568002',
        category: 'Beauty & Personal Care',
        purchasePrice: 65.00,
        price: 99.99,
        stock: 250,
        stockUnit: 'pcs',
        supplier: 'Dental Care',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Toothpaste)',
      ),
      InventoryProductModel(
        id: 'prod_114',
        name: 'Shampoo (250ml)',
        sku: 'SKU-BP-114',
        barcode: '8901234568003',
        category: 'Beauty & Personal Care',
        purchasePrice: 135.00,
        price: 199.99,
        stock: 200,
        stockUnit: 'pcs',
        supplier: 'Hair Care',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Shampoo)',
      ),
      InventoryProductModel(
        id: 'prod_115',
        name: 'Deodorant Spray',
        sku: 'SKU-BP-115',
        barcode: '8901234568004',
        category: 'Beauty & Personal Care',
        purchasePrice: 102.00,
        price: 149.99,
        stock: 220,
        stockUnit: 'pcs',
        supplier: 'Fresh Scents',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Deodorant)',
      ),
      InventoryProductModel(
        id: 'prod_116',
        name: 'Conditioner (250ml)',
        sku: 'SKU-BP-116',
        barcode: '8901234568005',
        category: 'Beauty & Personal Care',
        purchasePrice: 135.00,
        price: 199.99,
        stock: 180,
        stockUnit: 'pcs',
        supplier: 'Hair Care',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Conditioner)',
      ),
      InventoryProductModel(
        id: 'prod_117',
        name: 'Body Wash (500ml)',
        sku: 'SKU-BP-117',
        barcode: '8901234568006',
        category: 'Beauty & Personal Care',
        purchasePrice: 100.00,
        price: 150.00,
        stock: 200,
        stockUnit: 'pcs',
        supplier: 'Body Care',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Body+Wash)',
      ),
      InventoryProductModel(
        id: 'prod_118',
        name: 'Sunscreen (200ml)',
        sku: 'SKU-BP-118',
        barcode: '8901234568007',
        category: 'Beauty & Personal Care',
        purchasePrice: 210.00,
        price: 299.99,
        stock: 150,
        stockUnit: 'pcs',
        supplier: 'Sun Care',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Sunscreen)',
      ),

      // ===== HEALTH & WELLNESS (6 products) =====
      InventoryProductModel(
        id: 'prod_119',
        name: 'Vitamin C Tablets (60 pcs)',
        sku: 'SKU-HW-119',
        barcode: '8901234568008',
        category: 'Health & Wellness',
        purchasePrice: 210.00,
        price: 299.99,
        stock: 120,
        stockUnit: 'pcs',
        supplier: 'Health Plus',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Vitamins)',
      ),
      InventoryProductModel(
        id: 'prod_120',
        name: 'Protein Powder (500g)',
        sku: 'SKU-HW-120',
        barcode: '8901234568009',
        category: 'Health & Wellness',
        purchasePrice: 420.00,
        price: 599.99,
        stock: 100,
        stockUnit: 'pcs',
        supplier: 'Fitness Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Protein)',
      ),
      InventoryProductModel(
        id: 'prod_121',
        name: 'Multivitamin (30 pcs)',
        sku: 'SKU-HW-121',
        barcode: '8901234568010',
        category: 'Health & Wellness',
        purchasePrice: 280.00,
        price: 399.99,
        stock: 150,
        stockUnit: 'pcs',
        supplier: 'Health Plus',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Multivitamin)',
      ),
      InventoryProductModel(
        id: 'prod_122',
        name: 'Omega 3 Capsules (60 pcs)',
        sku: 'SKU-HW-122',
        barcode: '8901234568011',
        category: 'Health & Wellness',
        purchasePrice: 350.00,
        price: 499.99,
        stock: 100,
        stockUnit: 'pcs',
        supplier: 'Health Plus',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Omega+3)',
      ),
      InventoryProductModel(
        id: 'prod_123',
        name: 'Glucose Meter Test Strips (50 pcs)',
        sku: 'SKU-HW-123',
        barcode: '8901234568012',
        category: 'Health & Wellness',
        purchasePrice: 280.00,
        price: 399.99,
        stock: 80,
        stockUnit: 'pcs',
        supplier: 'Medical Supply',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Test+Strips)',
      ),
      InventoryProductModel(
        id: 'prod_124',
        name: 'First Aid Kit',
        sku: 'SKU-HW-124',
        barcode: '8901234568013',
        category: 'Health & Wellness',
        purchasePrice: 420.00,
        price: 599.99,
        stock: 90,
        stockUnit: 'pcs',
        supplier: 'Medical Supply',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=First+Aid)',
      ),

      // ===== BABY PRODUCTS (6 products) =====
      InventoryProductModel(
        id: 'prod_125',
        name: 'Baby Diaper Pack (30 pcs)',
        sku: 'SKU-BY-125',
        barcode: '8901234568014',
        category: 'Baby Products',
        purchasePrice: 285.00,
        price: 399.99,
        stock: 200,
        stockUnit: 'pcs',
        supplier: 'Baby Care',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Diaper)',
      ),
      InventoryProductModel(
        id: 'prod_126',
        name: 'Baby Milk Formula',
        sku: 'SKU-BY-126',
        barcode: '8901234568015',
        category: 'Baby Products',
        purchasePrice: 680.00,
        price: 899.99,
        stock: 120,
        stockUnit: 'pcs',
        supplier: 'Nutrition Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Formula)',
      ),
      InventoryProductModel(
        id: 'prod_127',
        name: 'Baby Bath Soap',
        sku: 'SKU-BY-127',
        barcode: '8901234568016',
        category: 'Baby Products',
        purchasePrice: 130.00,
        price: 199.99,
        stock: 180,
        stockUnit: 'pcs',
        supplier: 'Baby Care',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Baby+Soap)',
      ),
      InventoryProductModel(
        id: 'prod_128',
        name: 'Baby Bottle (250ml)',
        sku: 'SKU-BY-128',
        barcode: '8901234568017',
        category: 'Baby Products',
        purchasePrice: 210.00,
        price: 299.99,
        stock: 150,
        stockUnit: 'pcs',
        supplier: 'Baby Gear',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Bottle)',
      ),
      InventoryProductModel(
        id: 'prod_129',
        name: 'Wet Wipes Pack (100 pcs)',
        sku: 'SKU-BY-129',
        barcode: '8901234568018',
        category: 'Baby Products',
        purchasePrice: 100.00,
        price: 149.99,
        stock: 250,
        stockUnit: 'pcs',
        supplier: 'Hygiene Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Wipes)',
      ),
      InventoryProductModel(
        id: 'prod_130',
        name: 'Baby Stroller',
        sku: 'SKU-BY-130',
        barcode: '8901234568019',
        category: 'Baby Products',
        purchasePrice: 4500.00,
        price: 5999.99,
        stock: 30,
        stockUnit: 'pcs',
        supplier: 'Baby Gear',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Stroller)',
      ),

      // ===== SPORTS & OUTDOORS (8 products) =====
      InventoryProductModel(
        id: 'prod_131',
        name: 'Yoga Mat',
        sku: 'SKU-SP-131',
        barcode: '8901234568020',
        category: 'Sports & Outdoors',
        purchasePrice: 560.00,
        price: 799.99,
        stock: 75,
        stockUnit: 'pcs',
        supplier: 'Fitness Gear',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Yoga+Mat)',
      ),
      InventoryProductModel(
        id: 'prod_132',
        name: 'Dumbbells (5kg pair)',
        sku: 'SKU-SP-132',
        barcode: '8901234568021',
        category: 'Sports & Outdoors',
        purchasePrice: 1450.00,
        price: 1999.99,
        stock: 50,
        stockUnit: 'pcs',
        supplier: 'Equipment Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Dumbbells)',
      ),
      InventoryProductModel(
        id: 'prod_133',
        name: 'Cricket Bat',
        sku: 'SKU-SP-133',
        barcode: '8901234568022',
        category: 'Sports & Outdoors',
        purchasePrice: 1800.00,
        price: 2499.99,
        stock: 40,
        stockUnit: 'pcs',
        supplier: 'Sports Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Bat)',
      ),
      InventoryProductModel(
        id: 'prod_134',
        name: 'Tennis Ball Pack',
        sku: 'SKU-SP-134',
        barcode: '8901234568023',
        category: 'Sports & Outdoors',
        purchasePrice: 210.00,
        price: 299.99,
        stock: 100,
        stockUnit: 'pcs',
        supplier: 'Sports Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Tennis)',
      ),
      InventoryProductModel(
        id: 'prod_135',
        name: 'Bicycle Helmet',
        sku: 'SKU-SP-135',
        barcode: '8901234568024',
        category: 'Sports & Outdoors',
        purchasePrice: 1080.00,
        price: 1499.99,
        stock: 65,
        stockUnit: 'pcs',
        supplier: 'Safety Gear',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Helmet)',
      ),
      InventoryProductModel(
        id: 'prod_136',
        name: 'Swimming Goggles',
        sku: 'SKU-SP-136',
        barcode: '8901234568025',
        category: 'Sports & Outdoors',
        purchasePrice: 420.00,
        price: 599.99,
        stock: 90,
        stockUnit: 'pcs',
        supplier: 'Swimming Gear',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Goggles)',
      ),
      InventoryProductModel(
        id: 'prod_137',
        name: 'Badminton Racket',
        sku: 'SKU-SP-137',
        barcode: '8901234568026',
        category: 'Sports & Outdoors',
        purchasePrice: 920.00,
        price: 1299.99,
        stock: 70,
        stockUnit: 'pcs',
        supplier: 'Sports Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Racket)',
      ),
      InventoryProductModel(
        id: 'prod_138',
        name: 'Camping Tent (2 person)',
        sku: 'SKU-SP-138',
        barcode: '8901234568027',
        category: 'Sports & Outdoors',
        purchasePrice: 2900.00,
        price: 3999.99,
        stock: 35,
        stockUnit: 'pcs',
        supplier: 'Camping Gear',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Tent)',
      ),

      // ===== OFFICE SUPPLIES (8 products) =====
      InventoryProductModel(
        id: 'prod_139',
        name: 'A4 Paper Ream (500 sheets)',
        sku: 'SKU-OF-139',
        barcode: '8901234568028',
        category: 'Office Supplies',
        purchasePrice: 210.00,
        price: 299.99,
        stock: 100,
        stockUnit: 'pcs',
        supplier: 'Paper Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Paper)',
      ),
      InventoryProductModel(
        id: 'prod_140',
        name: 'Ballpoint Pen (Pack of 10)',
        sku: 'SKU-OF-140',
        barcode: '8901234568029',
        category: 'Office Supplies',
        purchasePrice: 50.00,
        price: 75.00,
        stock: 300,
        stockUnit: 'pcs',
        supplier: 'Writing Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Pen)',
      ),
      InventoryProductModel(
        id: 'prod_141',
        name: 'Stapler Machine',
        sku: 'SKU-OF-141',
        barcode: '8901234568030',
        category: 'Office Supplies',
        purchasePrice: 280.00,
        price: 399.99,
        stock: 60,
        stockUnit: 'pcs',
        supplier: 'Office Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Stapler)',
      ),
      InventoryProductModel(
        id: 'prod_142',
        name: 'Sticky Notes Pad',
        sku: 'SKU-OF-142',
        barcode: '8901234568031',
        category: 'Office Supplies',
        purchasePrice: 32.00,
        price: 49.99,
        stock: 400,
        stockUnit: 'pcs',
        supplier: 'Notes Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Notes)',
      ),
      InventoryProductModel(
        id: 'prod_143',
        name: 'File Folder',
        sku: 'SKU-OF-143',
        barcode: '8901234568032',
        category: 'Office Supplies',
        purchasePrice: 68.00,
        price: 99.99,
        stock: 250,
        stockUnit: 'pcs',
        supplier: 'Storage Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Folder)',
      ),
      InventoryProductModel(
        id: 'prod_144',
        name: 'Highlighter Pen (Pack of 6)',
        sku: 'SKU-OF-144',
        barcode: '8901234568033',
        category: 'Office Supplies',
        purchasePrice: 60.00,
        price: 89.99,
        stock: 200,
        stockUnit: 'pcs',
        supplier: 'Writing Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Highlighter)',
      ),
      InventoryProductModel(
        id: 'prod_145',
        name: 'Notebook (100 pages)',
        sku: 'SKU-OF-145',
        barcode: '8901234568034',
        category: 'Office Supplies',
        purchasePrice: 52.00,
        price: 79.99,
        stock: 280,
        stockUnit: 'pcs',
        supplier: 'Stationery Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Notebook)',
      ),
      InventoryProductModel(
        id: 'prod_146',
        name: 'Correction Fluid (20ml)',
        sku: 'SKU-OF-146',
        barcode: '8901234568035',
        category: 'Office Supplies',
        purchasePrice: 38.00,
        price: 59.99,
        stock: 220,
        stockUnit: 'pcs',
        supplier: 'Writing Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Correction+Fluid)',
      ),

      // ===== HOME DECOR (6 products) =====
      InventoryProductModel(
        id: 'prod_147',
        name: 'Wall Paint (1L)',
        sku: 'SKU-HD-147',
        barcode: '8901234568036',
        category: 'Home Decor',
        purchasePrice: 210.00,
        price: 299.99,
        stock: 80,
        stockUnit: 'liter',
        supplier: 'Paint Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Paint)',
      ),
      InventoryProductModel(
        id: 'prod_148',
        name: 'Bed Sheets (Double)',
        sku: 'SKU-HD-148',
        barcode: '8901234568037',
        category: 'Home Decor',
        purchasePrice: 650.00,
        price: 899.99,
        stock: 60,
        stockUnit: 'pcs',
        supplier: 'Bedding Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Sheets)',
      ),
      InventoryProductModel(
        id: 'prod_149',
        name: 'Pillow Case',
        sku: 'SKU-HD-149',
        barcode: '8901234568038',
        category: 'Home Decor',
        purchasePrice: 210.00,
        price: 299.99,
        stock: 120,
        stockUnit: 'pcs',
        supplier: 'Bedding Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Pillow)',
      ),
      InventoryProductModel(
        id: 'prod_150',
        name: 'Door Mat',
        sku: 'SKU-HD-150',
        barcode: '8901234568039',
        category: 'Home Decor',
        purchasePrice: 280.00,
        price: 399.99,
        stock: 100,
        stockUnit: 'pcs',
        supplier: 'Home Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Door+Mat)',
      ),
      InventoryProductModel(
        id: 'prod_151',
        name: 'Wall Clock',
        sku: 'SKU-HD-151',
        barcode: '8901234568040',
        category: 'Home Decor',
        purchasePrice: 420.00,
        price: 599.99,
        stock: 75,
        stockUnit: 'pcs',
        supplier: 'Clock Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Clock)',
      ),
      InventoryProductModel(
        id: 'prod_152',
        name: 'Picture Frame',
        sku: 'SKU-HD-152',
        barcode: '8901234568041',
        category: 'Home Decor',
        purchasePrice: 245.00,
        price: 349.99,
        stock: 140,
        stockUnit: 'pcs',
        supplier: 'Frame Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Frame)',
      ),

      // ===== BOOKS & MEDIA (4 products) =====
      InventoryProductModel(
        id: 'prod_153',
        name: 'English Novel',
        sku: 'SKU-BK-153',
        barcode: '8901234568042',
        category: 'Books & Media',
        purchasePrice: 210.00,
        price: 299.99,
        stock: 100,
        stockUnit: 'pcs',
        supplier: 'Book Store',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Novel)',
      ),
      InventoryProductModel(
        id: 'prod_154',
        name: 'Self-Help Book',
        sku: 'SKU-BK-154',
        barcode: '8901234568043',
        category: 'Books & Media',
        purchasePrice: 280.00,
        price: 399.99,
        stock: 80,
        stockUnit: 'pcs',
        supplier: 'Book Store',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Self+Help)',
      ),
      InventoryProductModel(
        id: 'prod_155',
        name: 'Magazine (Monthly)',
        sku: 'SKU-BK-155',
        barcode: '8901234568044',
        category: 'Books & Media',
        purchasePrice: 68.00,
        price: 100.00,
        stock: 200,
        stockUnit: 'pcs',
        supplier: 'Magazine Co',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Magazine)',
      ),
      InventoryProductModel(
        id: 'prod_156',
        name: 'Textbook',
        sku: 'SKU-BK-156',
        barcode: '8901234568045',
        category: 'Books & Media',
        purchasePrice: 350.00,
        price: 499.99,
        stock: 60,
        stockUnit: 'pcs',
        supplier: 'Book Store',
        imageUrl:
            '[via.placeholder.com](https://via.placeholder.com/300?text=Textbook)',
      ),
    ];
  }
}
