// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoztuVQp2RMSqCWvT9_F9oD4t4cdtT9o0',
    appId: '1:462217458182:web:100283e925610ca83a0987',
    messagingSenderId: '462217458182',
    projectId: 'billing-c95f5',
    authDomain: 'billing-c95f5.firebaseapp.com',
    storageBucket: 'billing-c95f5.firebasestorage.app',
    measurementId: 'G-XFN34D83VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4oDtTMSKVrhlRbFWqtUi8r_DNWTonM0Q',
    appId: '1:462217458182:android:90bb655944daf4a53a0987',
    messagingSenderId: '462217458182',
    projectId: 'billing-c95f5',
    storageBucket: 'billing-c95f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRrjj8ZnEZguWuilKd5QRyXvzIxxKmpvA',
    appId: '1:462217458182:ios:fdbb7f277bddb1c33a0987',
    messagingSenderId: '462217458182',
    projectId: 'billing-c95f5',
    storageBucket: 'billing-c95f5.firebasestorage.app',
    iosBundleId: 'com.example.billingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRrjj8ZnEZguWuilKd5QRyXvzIxxKmpvA',
    appId: '1:462217458182:ios:fdbb7f277bddb1c33a0987',
    messagingSenderId: '462217458182',
    projectId: 'billing-c95f5',
    storageBucket: 'billing-c95f5.firebasestorage.app',
    iosBundleId: 'com.example.billingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoztuVQp2RMSqCWvT9_F9oD4t4cdtT9o0',
    appId: '1:462217458182:web:733bfd8c83d8b6693a0987',
    messagingSenderId: '462217458182',
    projectId: 'billing-c95f5',
    authDomain: 'billing-c95f5.firebaseapp.com',
    storageBucket: 'billing-c95f5.firebasestorage.app',
    measurementId: 'G-3ZBV14W4NZ',
  );
}
