name: Deploy Web App

on:
  push:
    branches:
      - main
      - digital-heroes-assignment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.3"
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Generate Launcher Icons
        run: dart run flutter_launcher_icons

      - name: Generate Native Splash
        run: dart run flutter_native_splash:create

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy \
            --only hosting \
            --token "$FIREBASE_TOKEN"